/* Uniforms */

"LOP_U_RACS_Fatigue_01"
,"LOP_U_RACS_Fatigue_01_slv"
,"LOP_U_AFR_Fatigue_04_slv"
,"LOP_U_AFR_Fatigue_04"
,"rhs_uniform_cu_ocp"
,"rhs_uniform_cu_ucp"
,"rhs_uniform_FROG01_m81"
,"rhs_uniform_gorka_r_y"
,"CUP_U_B_USMC_PilotOverall"


/* Vest */

,"LOP_V_CarrierLite_OLV"
,"LOP_V_CarrierRig_OLV"
,"V_PlateCarrierL_CTRG"
,"V_PlateCarrierH_CTRG"
,"rhsusf_iotv_ocp_Grenadier"
,"rhsusf_iotv_ucp_Grenadier"
,"rhsusf_iotv_ocp_Medic"
,"rhsusf_iotv_ucp_Medic"
,"rhsusf_iotv_ocp_Repair"
,"rhsusf_iotv_ucp_Repair"
,"rhsusf_iotv_ocp_Rifleman"
,"rhsusf_iotv_ucp_Rifleman"
,"rhsusf_iotv_ocp_SAW"
,"rhsusf_iotv_ucp_SAW"
,"rhsusf_iotv_ocp_Squadleader"
,"rhsusf_iotv_ucp_Squadleader"
,"rhsusf_iotv_ocp_Teamleader"
,"rhsusf_iotv_ucp_Teamleader"
,"rhsusf_spc_iar"
,"rhsusf_spc_light"
,"rhsusf_spc_mg"
,"rhsusf_spc_marksman"
,"rhsusf_spc_rifleman"
,"rhsusf_spc_squadleader"
,"rhsusf_spc_teamleader"
,"V_PlateCarrier1_blk"
,"V_PlateCarrier1_rgr"
,"V_PlateCarrier2_blk"
,"V_PlateCarrier2_rgr"
,"LOP_V_6B23_6Sh92_OLV"
,"LOP_V_6Sh92_Radio_OLV"
,"LOP_V_6Sh92_Vog_OLV"
,"CUP_V_B_PilotVest"


/* Headgear */

,"CUP_H_USMC_Helmet_Pilot"
,"LOP_H_6B27M_RACS"
,"LOP_H_6B27M_ess_RACS"
,"rhsusf_ach_bare_wood_headset"
,"rhsusf_ach_bare_wood_headset_ess"
,"rhsusf_ach_helmet_headset_ocp"
,"rhsusf_ach_helmet_headset_ucp"
,"rhsusf_ach_helmet_headset_ess_ucp"
,"rhsusf_ach_helmet_headset_ess_ocp"
,"rhsusf_mich_bare_norotos_arc_alt_headset"
,"rhsusf_mich_bare_norotos_arc_alt_tan_headset"
,"rhsusf_mich_bare_norotos_arc_alt_tan"
,"LOP_H_Pakol"
,"H_Cap_headphones"
,"H_HelmetCrew_I"
,"rhs_Booniehat_ocp"
,"rhs_Booniehat_ucp"
,"rhs_Booniehat_m81"
,"LOP_H_Booniehat_RACS"
,"H_Booniehat_tan"
,"H_Booniehat_khk_hs"
,"H_Watchcap_blk"
,"LOP_H_6B27M_UN



/* Backpack */

,"B_AssaultPack_cbr"
,"B_AssaultPack_rgr"
,"B_AssaultPack_mcamo"
,"CUP_B_Bergen_BAF"
,"rhsusf_assault_eagleaiii_ocp"
,"rhsusf_assault_eagleaiii_ucp"
,"rhs_rpg_empty"
,"CUP_B_GER_Medic_Desert"


/* Items */

,"ItemMap"
,"ItemCompass"
,"ItemWatch"
,"Laserdesignator_03"
,"ItemcTab"
,"ACE_Vector"
,"Laserdesignator_03"
,"Laserbatteries"
,"Binocular"

/* Handguns */

,"rhsusf_weap_glock17g4"
,"rhsusf_mag_17Rnd_9x19_JHP"
,"rhsusf_mag_17Rnd_9x19_FMJ"
,"rhs_weap_M320"
,"rhs_mag_M441_HE"
,"rhs_mag_M433_HEDP"
,"CUP_hgun_M9"
,"CUP_15Rnd_9x19_M9"
,"CUP_muzzle_snds_M9"
,"hgun_ACPC2_F"
,"9Rnd_45ACP_Mag"
,"muzzle_snds_acp"


/* Launchers */

,"rhs_weap_M136"
,"rhs_m136_mag"
,"rhs_weap_M136_hedp"
,"rhs_m136_hedp_mag"
,"rhs_weap_M136_hp"
,"rhs_m136_hp_mag"
,"rhs_weap_smaw_green"
,"rhs_mag_smaw_HEAA"
,"rhs_weap_optic_smaw"
,"rhs_mag_smaw_HEDP"
,"rhs_mag_smaw_SR"
,"rhs_weap_rpg7"
,"rhs_rpg7_PG7VL_mag"
,"rhs_acc_pgo7v"
,"rhs_rpg7_PG7VR_mag"
,"rhs_rpg7_OG7V_mag"
,"rhs_rpg7_TBG7V_mag"
,"rhs_weap_rshg2"
,"rhs_rshg2_mag"
,"rhs_weap_fgm148"
,"rhs_fgm148_magazine_AT"



/* Weapons */

,"SMG_01_F"
,"30Rnd_45ACP_Mag_SMG_01"
,"muzzle_snds_acp"
,"rhs_weap_svdp_wd"
,"rhs_10Rnd_762x54mmR_7N1"
,"rhs_acc_pso1m2"
,"rhs_weap_pkm"
,"rhs_100Rnd_762x54mmR"
,"rhs_100Rnd_762x54mmR_green"
,"CUP_smg_MP5SD6"
,"CUP_30Rnd_9x19_MP5"
,"CUP_srifle_Mk12SPR"
,"CUP_20Rnd_556x45_Stanag"
,"CUP_muzzle_snds_M16"
,"CUP_optic_SB_11_4x20_PM"
,"bipod_01_F_blk"
,"30Rnd_556x45_Stanag"
,"CUP_30Rnd_556x45_Stanag"
,"20Rnd_762x51_Mag"
,"optic_DMS"
,"rhs_weap_M590_8RD"
,"rhsusf_8Rnd_Slug"
,"rhsusf_8Rnd_00Buck"
,"rhs_weap_m4a1_carryhandle_m203S"
,"rhs_mag_30Rnd_556x45_Mk318_Stanag"
,"rhsusf_acc_nt4_black"
,"rhsusf_acc_anpeq15A"
,"rhsusf_acc_ACOG3_USMC"
,"rhs_weap_m4a1_carryhandle_m203"
,"rhs_mag_M433_HEDP"
,"rhs_mag_M441_HE"
,"1Rnd_SmokeOrange_Grenade_shell"
,"1Rnd_SmokeBlue_Grenade_shell"
,"1Rnd_SmokePurple_Grenade_shell"
,"1Rnd_SmokeYellow_Grenade_shell"
,"1Rnd_SmokeGreen_Grenade_shell"
,"1Rnd_SmokeRed_Grenade_shell"
,"1Rnd_Smoke_Grenade_shell"
,"UGL_FlareCIR_F"
,"UGL_FlareYellow_F"
,"UGL_FlareRed_F"
,"UGL_FlareGreen_F"
,"UGL_FlareWhite_F"
,"1Rnd_HE_Grenade_shell"
,"rhs_weap_m4a1_carryhandle_grip"
,"rhs_weap_m4a1_carryhandle_grip2"
,"rhsusf_acc_anpeq15side"
,"rhs_weap_m4a1_carryhandle_pmag"
,"rhs_weap_m4a1_carryhandle_grip"
,"rhsusf_acc_ELCAN"
,"rhsusf_acc_ACOG"
,"rhsusf_acc_eotech_552"
,"CUP_optic_CompM4"
,"CUP_optic_MRad"
,"optic_Holosight"
,"CUP_optic_TrijiconRx01_black"
,"optic_NVS"
,"acc_flashlight"
,"rhs_weap_m249_pip_S_para"
,"rhs_200rnd_556x45_M_SAW"
,"rhs_200rnd_556x45_B_SAW"
,"rhs_200rnd_556x45_T_SAW"
,"rhsusf_100Rnd_556x45_soft_pouch"
,"rhsusf_200Rnd_556x45_soft_pouch"
,"rhs_weap_m249_pip_L"
,"rhs_weap_m240B"
,"rhsusf_50Rnd_762x51"
,"rhsusf_100Rnd_762x51"
,"rhsusf_100Rnd_762x51_m62_tracer"
,"rhsusf_100Rnd_762x51_m61_ap"
,"CUP_srifle_M24_des"
,"CUP_5Rnd_762x51_M24"
,"CUP_optic_LeupoldMk4_10x40_LRT_Desert"
,"rhs_weap_m16a4_carryhandle_M203"
,"rhs_weap_m16a4_carryhandle_grip"
,"rhs_weap_m16a4_carryhandle"
,"rhs_weap_m14ebrri"
,"rhsusf_20Rnd_762x51_m118_special_Mag"
,"rhsusf_20Rnd_762x51_m993_Mag"
,"rhs_weap_asval"
,"rhs_20rnd_9x39mm_SP5"
,"rhs_acc_pkas"
,"rhs_20rnd_9x39mm_SP6"
,"rhs_weap_akm_gp25"
,"rhs_30Rnd_762x39mm"
,"rhs_VG40OP_white"
,"rhs_VG40OP_green"
,"rhs_VG40OP_red"
,"rhs_GRD40_White"
,"rhs_GRD40_Green"
,"rhs_GRD40_Red"
,"rhs_VG40MD_White"
,"rhs_VG40MD_Green"
,"rhs_VG40MD_Red"
,"rhs_GDM40"
,"rhs_weap_akms
,"rhs_acc_2dpZenit"
,"rhs_acc_pbs1"
,"rhs_weap_ak74m_gp25_npz"
,"rhs_30Rnd_545x39_AK"
,"rhs_acc_tgpa"
,"rhs_weap_ak74m_desert_npz"
,"rhs_acc_dtk"
